### ISSUE TITLE
Consider including react-window

### ISSUE THREAD

**Issue by shaneosullivan** [domenic/infinite-list-study-group#7]
The latest infinite scrolling library from the React team appears to be highly performant, with including in this study

https://react-window.now.sh/

**Comment by domenic** [comment]
That'd be great. Would you be interested in submitting a study?

**Comment by shaneosullivan** [comment]
I may not be the best person to do so.  I'll point Brian, the author of React Window here and see if he's interested.

**Comment by bvaughn** [comment]
Hi 👋 Sounds interesting. I don't have a lot of bandwidth at the moment to "submit a study" (sounds involved) but maybe I can free some time up over the next few weeks. It depends on the timing requirements, I suppose?

**Comment by domenic** [comment]
Hey folks! We're consolidating this repository with https://github.com/WICG/virtual-scroller, and moved all studies into https://github.com/WICG/virtual-scroller/tree/master/study-group.

I'll close this issue as part of the general repository shutdown, but feel free to submit a study, or otherwise engage, over there. (I'll note that @bvaughn has already been helping a lot behind the scenes.)
